# Generated by Django 5.1.6 on 2025-02-18 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_createdat_user_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('read', 'Read'), ('write', 'Write')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_by_weblink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_shares', to='database.weblink')),
                ('shared_with_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to='database.user')),
            ],
            options={
                'db_table': 'shares',
                'unique_together': {('shared_with_user', 'shared_by_weblink')},
            },
        ),
    ]
